{
 "title": "recipe-api",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "route",
    "query": "SHOW TAG VALUES  WITH KEY = \"route\" WHERE \"project\"='sfl-engine'"
   },
   { "name": "adhoc" },
   { "name": "statusCode", "label": "http status code", "query": "200,300,400,500" }
  ]
 },
 "panels": [
  {
   "title": "Secondary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "recipe offers(create &  upload to s3)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_route($tag_status)",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "route" ], "type": "tag" }
       ],
       "measurement": "sfl-engine_request",
       "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /recipe_offers_*/) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
       "select": [
        [
         { "params": [ "code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=", "value": "sfl-engine" },
        { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
        { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
        { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
       ]
      }
     ]
    },
    {
     "title": "recipe campaigns(create &  upload to s3)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_route($tag_status)",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "route" ], "type": "tag" }
       ],
       "measurement": "sfl-engine_request",
       "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /recipe_campaigns_*/) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
       "select": [
        [
         { "params": [ "code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=", "value": "sfl-engine" },
        { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
        { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
        { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
       ]
      }
     ]
    },
    {
     "title": "all request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_route($tag_status)",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "route" ], "type": "tag" }
       ],
       "measurement": "sfl-engine_request",
       "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe' AND \"status\" =~ /^$statusCode$/) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
       "select": [
        [
         { "params": [ "code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=", "value": "sfl-engine" },
        { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Error 500",
   "type": "graph",
   "description": "co-recipe Error 500 alert",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe' AND \"status\" = '500') AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "500" }
     ]
    }
   ]
  },
  {
   "title": "[Master] Generate OFFERS data for create  recipe",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /generate_recipe_offers_recipe-api-master-prod-1_master*/  ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "[Master] Generate CAMPAIGNS data for create  recipe",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /generate_recipe_campaigns_recipe-api-master-prod-1_master*/  ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "[Slave] Generate OFFERS data for create  recipe",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /generate_recipe_offers_recipe-api-slave-prod-1_slave*/  ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "[Slave] Generate CAMPAIGNS data for create  recipe",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /generate_recipe_campaigns_recipe-api-slave-prod-1*/  ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "[MASTER] Generate AFFILIATES data for create  recipe",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /generate_recipe_affiliates_*/  ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "[Slave] Generate AFFILIATES data for create  recipe",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /generate_recipe_affiliates_*/  ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "Created offer recipe  ",
   "type": "graph",
   "description": "Created offer recipe  ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /recipe_offers_created_*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "Created campaign recipe  ",
   "type": "graph",
   "description": "Created campaign recipe  ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /recipe_campaigns_created_*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "recipe offer uploaded to s3",
   "type": "graph",
   "description": "recipe offer uploaded to s3",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /recipe_offers_uploaded*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "recipe campaign uploaded to s3",
   "type": "graph",
   "description": "recipe campaign uploaded to s3",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /recipe_campaigns_uploaded*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "UPD redshift table affilaites",
   "type": "graph",
   "description": "UPD redshift table affilaites",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /copy_file_s3_affiliates_to_redshift_success_*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "traffic-api connected   ",
   "type": "graph",
   "description": "traffic-api connected   ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /connect_traffic_api_*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "UPD redshift table offers",
   "type": "graph",
   "description": "UPD redshift table offers",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /copy_file_s3_offers*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "UPD redshift table campaigns",
   "type": "graph",
   "description": "UPD redshift table campaigns",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /copy_file_s3_campaigns_*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "ssoAuth_system",
     "query": "SELECT \"cpu_avg_perc\" FROM \"co_recipe_system\" WHERE (\"project\" = 'co_recipe') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "cpu_avg_perc" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage (RAM) % (Percent)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host (Used Mem)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "ssoAuth_system",
     "query": "SELECT \"mem_os_usage\" FROM \"co_recipe_system\" WHERE (\"project\" = 'co_recipe') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "mem_os_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "ssoAuth" }
     ]
    }
   ]
  },
  {
   "title": "data was changed and recipe created ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /recipe_campaigns_created*/ OR  \"route\" =~ /recipe_offers_created*/) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "set_file_size_redis_",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /set_file_size_redis_*/) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "file size changed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200'    AND \"route\" =~ /file_size_changed*/) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  },
  {
   "title": "SQS ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200' AND \"route\" =~ /sqs_campaign*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    },
    {
     "alias": "$tag_route($tag_status)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "sfl-engine_request",
     "query": "SELECT count(\"code\") FROM \"co_recipe_request\" WHERE (\"project\" = 'co_recipe'   AND \"status\" ='200' AND \"route\" =~ /sqs_offer*/ ) AND $timeFilter GROUP BY time(1m), \"status\", \"route\"",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sfl-engine" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$statusCode$/" },
      { "condition": "AND", "key": "route", "operator": "=~", "value": "/platform*/" },
      { "condition": "AND", "key": "route", "operator": "!~", "value": "/found*/" }
     ]
    }
   ]
  }
 ]
}